### ISSUE TITLE
[BUG] `tr[choice]` syntax no longer works in genjax 0.4

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1177]
It appears that `tr['choice']` triggers an error in genjax 0.4.  The syntax `tr.get_choices()['choice']` works, however.

(It is possible that this is intentional, but my guess is that the intention is still to support `tr['choice']`, so I'm filing as a bug.)

Minimal working example:
```python
import jax
import genjax

@genjax.gen
def foo():
  x = genjax.flip(0.5) @ "x"

tr = foo.simulate(jax.random.PRNGKey(0), ())
tr["x"] # Triggers error `TypeError: 'StaticTrace' object is not subscriptable`
```

**Comment by sritchie** [comment]
Hey @georgematheos , we've been discussing this — this absolutely would have been a great change to design and announce, but we blew it and have now forced everyone to adapt to the new style.

We're going to keep the current behavior for now, in favor of forcing folks to call `get_choices()`; `get_choices()` can be expensive, and rather than implement `[]` on traces by internally calling `get_choices()` and caching the result, it seems more efficient for memory and performance to have the user do this.

Let me know if this makes sense, obviously nothing's set in stone and if this has been a pain for you let's reconsider.
