### ISSUE TITLE
[BUG] "reverse" flag is broken w/ current update implementation

### ISSUE THREAD

**Issue by sritchie** [genjax-community/genjax#1254]
Noted by @femtomc , making this so we have a ticket to track a fix.

**Comment by sritchie** [comment]
@femtomc is this really broken if we consistently feed `reverse=True` everywhere? If I provide indexed updates, those affect the un-reversed input, which makes sense;

I get that we have to care when we take on incremental updates, since we want to only re-feed in the beginning of a vector vs the end. But what is broken now?

**Comment by femtomc** [comment]
Isn't there a count which we keep track of to figure out where to index into a choice map? In reverse=True, we're not starting at N and decrementing, we're still starting at 0 ... (therefore, we're still indexing into the choice map forwards -- as we scan backwards)

**Comment by sritchie** [comment]
But the choice map index 0 comes from the result, which starts at the end of the input, right?

**Comment by sritchie** [comment]
So indexing forwards into the choice map as we scan backwards makes sense I think?

**Comment by femtomc** [comment]
When we scan in the implementation (`jax.lax.scan`) -- we don't pass the choice map in as an argument to scan -- we close over it and index into it using the dynamic index -- which starts at 0. That's the problem.

The scan is not going over the choice map (because the choice map may not have lengths at the leaves equal to the full scan!) directly.
