### ISSUE TITLE
[BUG] ChoiceMapBuilder ignores paths for n, v, kw, d

### ISSUE THREAD

**Issue by sritchie** [genjax-community/genjax#1311]
imo the reason to use `ChoiceMapBuilder` is to make the static methods on `ChoiceMap` available at sub-paths.

`n`, `kw`, `d` and `v` are all currently ignoring the `paths` entry.

```python
>>> from genjax import ChoiceMapBuilder as C                                                  
>>> C["x", "y"].set(10)
StaticChm(c=StaticChm(c=ValueChm(v=10), addr='y'), addr='x')
>>> C["x", "y"].v(10)
ValueChm(v=10)
```

My suggestion here is to

- Move the logic of these over to class methods on `ChoiceMap`
- add a property to `ChoiceMap` like `builder` that exposes `ChoiceMapBuilder`, have this call `a` or something like that
- make `ChoiceMapBuilder` expose the class methods at leaves and have that be all it does.

**Comment by littleredcomputer** [comment]
I do see the point of allowing d, kw to nest inside the address that's already established (or we should warn the user that they're not getting what they may expect). Returning to this example, which works:
```
xy = C['x'].set(jnp.arange(10, 15)).at['y'].set(jnp.arange(15, 20))
cm = C[jnp.arange(5)].set(xy)
```
and produces an IdxChm, we could perhaps say
```
C[jnp.arange(5)].kw(x=jnp.arange(10, 15), y=jnp.arange(15,20))
```
if `kw` honored the address prefix upon which it was invoked

**Comment by femtomc** [comment]
I don't think there's anything semantically deep about this problem.

In other words, it's just a code organization issue -- it is busted, can we fix it with a refactor? I don't think we need to re-think the choice map DSL, just what methods ChoiceMapBuilder exposes (or if we even want to keep ChoiceMapBuilder around...)

The problem is -- we want to be able to use `(c :: ChoiceMap)["x", "y", ...]` (indexing on specific choice map instances) _and_ we want to be able to use `ChoiceMap["x", "y"]` (indexing to denote an address slice, which we want to set)

Can we just remove all the `n, v, kw, d` methods from ChoiceMapBuilder? And instead, expose a class property on `ChoiceMap` which allows users to access the builder (to use `ChoiceMapBuilder.set`)? That way, someone can't stumble into this weirdness (because `n` `v`, etc -- won't be defined on `ChoiceMapBuilder`)
