### ISSUE TITLE
[Sugar] Add `GenerativeFunction.sample` for sampling a retval

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1345]
A thought: we could have `GenerativeFunction.sample(key, *args)` be sugar for `GenerativeFunction.simulate(key, args).get_retval()`.

**Comment by vkmvkmvkmvkm** [comment]
I like this!

And if it isn’t a good idea, I’d like to better understand what I’m missing.

**Comment by femtomc** [comment]
Not a bad idea -- and we've proposed it in the past: https://github.com/probcomp/genjax/pull/857#issuecomment-1889862653

I think `sample_retval` is a slightly better name -- because it's a slightly uncommon operation (it doesn't provide much automation in the case of inference logic). Wdyt?

Step up to the plate George! Bring your kill to the fire.

**Comment by femtomc** [comment]
(@georgematheos note, to add this -- you'd just add it to our `GenerativeFunction` base class)

**Comment by sritchie** [comment]
I think what's you're asking for is implemented as `gen_fn(*args, **kwargs)(key)`. Passing the args to a generative function returns a `GenerativeFunctionClosure`, and calling that with a key will return a sample:

```python
@genjax.gen
def step(state, sigma):
    new_x = genjax.normal(state, sigma) @ "x"
    return (new_x, new_x + 1)

key = jax.random.PRNGKey(20)    
step(1.0, 2.0)(key)
```

returns

```python
(
<jax.Array(3.011287, dtype=float32)>,
<jax.Array(4.0112867, dtype=float32)>,
)
```

does that work for you, @georgematheos ?

**Comment by georgematheos** [comment]
Oh, that looks great @sritchie !
