### ISSUE TITLE
[BUG] Update and importance return traces with (presumably) different pytree shapes

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1352]
Minimal working example:

```python
import jax
import jax.random as r
import genjax
from genjax import ChoiceMapBuilder as C
from genjax import UpdateProblemBuilder as U
from genjax import Diff

@genjax.gen 
def foo(a):
    y = genjax.normal(a, 1.0) @ "y"
    return a + y

trace, w = foo.importance(r.PRNGKey(0), C.n(), (2.0,))
trace2, _, _, _ = trace.update(r.PRNGKey(0), U.g((Diff.no_change(2.),), C.kw(y=5.0)))

@jax.jit
def compile(trace):
    print("compiling")
    return 0

compile(trace) # Prints "compiling"

compile(trace) # Does not print 'compiling', as expected

compile(trace2) # Prints "compiliing" -- this seems wrong!  By jit compiling for `trace`, we should have already compiled for `trace2`.
```

**Comment by femtomc** [comment]
Will test today on main

**Comment by femtomc** [comment]
@georgematheos Found the issue -- the traces have identical structure, but because you didn't `jax.jit` the interface methods, the _leaves_ have different types (some are arrays, some are literal values, and some are array with [weak types](https://jax.readthedocs.io/en/latest/type_promotion.html#weakly-typed-values-in-jax)).

If any of these types (in the leaves of the Pytree -- the leaves of the trace) are mismatched, this induces the cache miss.

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/e1eb226f-9876-4090-bcaa-d0fdba4fdb62">

Note that, we haven't been careful about "weak versus strong types" in GenJAX -- so I suspect we actually should review how GenJAX induces these types internally... (@sritchie)

**Comment by femtomc** [comment]
@georgematheos Note that, if you ever want to check the equivalent of the structure of 2 pytrees -- you can use the `Pytree.static_check_tree_structure_equivalence` method:

```
    @staticmethod
    def static_check_tree_structure_equivalence(trees: list[Any]):
        if not trees:
            return True
        else:
            fst, *rest = trees
            treedef = jtu.tree_structure(fst)
            check = all(map(lambda v: treedef == jtu.tree_structure(v), rest))
            return check
```

<img width="567" alt="image" src="https://github.com/user-attachments/assets/45d26329-b5b6-4b48-b938-a6bbd515a80f">

But this check does not check the leaf dtypes, as far as I can tell.

**Comment by georgematheos** [comment]
This is super helpful!  Thanks @femtomc.

I think we now know how to fix this issue for ourselves (jitting the interface methods) -- feel free to close (or leave open if you want to address this for future users in some way, either by changes to genjax, or by adding this as a "gotcha" in the docs).

**Comment by sritchie** [comment]
I don't know what we can say about this for now in a general way... but it will be great to have this reference if it comes up again, and we'll figure out the weak type thing!
