### ISSUE TITLE
[BUG] `genjax.Switch` traces closed-over variables that should be static

### ISSUE THREAD

**Issue by midfield** [genjax-community/genjax#383]
**Describe the bug**
If you put a generative function into a `genjax.Switch` that has closed-over variables, they get traced.  This can be a problem if the closed-over variable is used as a shape.

This doesn't occur if the referenced variable is a global.

**To Reproduce**
This works:

```{python}
key = jax.random.PRNGKey(1337)
global_num = 10

@genjax.gen
def model(x):
  scale = jnp.linspace(0, 1, global_num).sum()
  data = genjax.normal(x, scale) @ 'data'
  return data

_, trace = genjax.simulate(model)(key, (5,))
print(trace.retval)

_, trace = genjax.simulate(genjax.Switch(model, model))(key, (0, 5))
print(trace.retval)

==>
2.5799105
2.5799105
```

This produces an error
```{python}
key = jax.random.PRNGKey(1337)

def make_model(closed=10):
  @genjax.gen
  def model(x):
    scale = jnp.linspace(0, 1, closed).sum()
    data = genjax.normal(x, scale) @ 'data'
    return data
  return model

model = make_model(10)

_, trace = genjax.simulate(model)(key, (5,))
print(trace.retval)

_, trace = genjax.simulate(genjax.Switch(model, model))(key, (0, 5))
print(trace.retval)

==>

2.5799105
...long traceback...
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: 
Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=2/0)>
'num' argument of jnp.linspace
The error occurred while tracing the function _apply at 
... for make_jaxpr. 
This concrete value was not available in Python because it depends on the value of the argument gen_fn[<flat index 
0>][<flat index 0>][0].

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```
**Expected behavior**
Closed-over variables should not be traced.

**Screenshots**
n/a

**Execution environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.11.4
 - GenJAX version: 0.0.1

**Additional context**
n/a

**Comment by femtomc** [comment]
@midfield is this blocking you ASAP? I'll be fully back to work tomorrow.

**Comment by midfield** [comment]
@femtomc This is for outlier models.  There are other things we can work on in the meantime, and we can work around it if we want to work on outlier models, but it is inconvenient since we use closures a lot.

**Comment by midfield** [comment]
New failing test case (even after #384)

```python
import jax
from jax import numpy as jnp
import genjax

key = jax.random.PRNGKey(1337)

def make_model(closed=10):
  @genjax.gen
  def model(x):
    scale = jnp.linspace(0, 1, closed).sum()
    data = genjax.normal(x, scale) @ 'data'
    return data
  return model

model = make_model(10)

def make_switcher(m1, m2):
  @genjax.gen
  def switcher(*args):
    flip = genjax.bernoulli(.5) @ 'flip'
    result = genjax.Switch(m1, m2)(jnp.int32(flip), *args) @ 'result'
    return result
  return switcher

_, trace = genjax.simulate(make_switcher(model, model))(key, (5,))
```

**Comment by midfield** [comment]
More test failing test cases, these do not use `Switch`

```python
import functools
import jax
from jax import numpy as jnp
import genjax

key = jax.random.PRNGKey(1337)

def model(num, x):
  scale = jnp.linspace(0, 1, num).sum()
  data = genjax.normal(x, scale) @ 'data'
  return data

_, trace = genjax.simulate(genjax.gen(model))(key, (10, 5))
print(trace.retval)


# doesn't work
_, trace = genjax.simulate(
    genjax.gen(functools.partial(model, 10)))(key, (5,))
print(trace.retval)

# doesn't work
model_partial = genjax.partial(genjax.gen(model), 10)
_, trace = genjax.simulate(model_partial)(key, (5,))
print(trace.retval)
```

**Comment by femtomc** [comment]
I just found the same reduction :)

**Comment by femtomc** [comment]
@midfield There are a few issues here:

* In these lines:
```python
_, trace = genjax.simulate(genjax.gen(model))(key, (10, 5))
print(trace.retval)
```
In the `BuiltinGenerativeFunction` language, GenJAX always lifts argument values to `Tracers`, so this should error because `5` becomes a `Tracer`, and the interface methods don't support `static_argnums` (or an equivalent) to prevent the lifting.

I'm not sure if we'll ever have an ergonomic solution to this, considering that transforms are critical for the `Builtin` language, and I'm hesitant to change the signatures of interface methods (complexifying the key interface concepts which Gen operates with). Hence, I recommended to you that you use closure generators.

Closure model generators seem like a good idea, so let's move onto the next two issues:

* `functools.partial` creates an object which doesn't expose `__closure__`, preventing us from reflecting on the environment. This will cause an error:
```python
# doesn't work
_, trace = genjax.simulate(
    genjax.gen(functools.partial(model, 10)))(key, (5,))
print(trace.retval)
```

I would like to figure out a way around this one. I suspect that `functools.partial` is so widely used, it's probably worth supporting it. I think this necessitates a change to `PytreeClosure`, but I have more comments about this object below.

* Ignoring the above, using `genjax.partial` -- the `PytreeClosure` objects which you might see in stack traces are designed to solve a simple use case: if we wish to return generative functions from JIT/JAX API boundaries, we have to be careful about closure environment keeping handles on tracers.

I suspect my implementation of `PytreeClosure` is "not good":

```python
@dataclass
class PytreeClosure(Pytree):
    callable: Callable
    environment: List

    def flatten(self):
        return (self.environment,), (self.callable,)

    def __call__(self, *args):
        print(self.environment)
        if self.callable.__closure__ is None:
            return self.callable(*args)
        else:
            for (cell, v) in zip(self.callable.__closure__, self.environment):
                cell.cell_contents = v
            ret = self.callable(*args)
            for cell in self.callable.__closure__:
                cell.cell_contents = None
            return ret
```

The idea here is to essentially pull the environment into something which JAX can zip/unzip as dynamic.

I suspect the root of the error is that one of my interpreter transforms is lifting the values of `self.environment` to `Tracer` type. What puzzles me is that the following works:

```python
def model_generator(num):
    @genjax.gen
    def model(x):
        scale = jnp.linspace(0, 1, num).sum()
        data = genjax.normal(x, scale) @ 'data'
        return data
    return model

model_generator(10).simulate(key, (5, ))
```

And here, I would expect a bug which had to do with accidentally lifting the closure environment to `Tracer` type would also affect this example.

But perhaps what is occurring is actually because we are using the closed over generative function inside the `trace` primitive. When I land, I'll investigate this possibility.

**Comment by femtomc** [comment]
Closed as completed.
