### ISSUE TITLE
[Defactor] Ordering of arguments and return values 

### ISSUE THREAD

**Issue by mirkoklukas** [genjax-community/genjax#479]
It would be great to order arguments and return values in `update` and `importance` etc in the same way as Gen.jl.
Furthermore, why do we replace `importance` by `generate`? 
A typical use of update is as follows
```python
(_, w, tr2, _) = tr1.update(key, ch, argdiffs(args))
```
or even 
```python
(_, _, tr2, _) = tr1.update(key, ch, argdiffs(args))
```
Why don't we order in a way that reflects the frequency of use or have some guidelines or copy Gen.jl's order, and also keep that consistent across everything. 

For `update` that would mean:
```python
(tr2,w,_, _) = tr1.update(key, argdiffs(args), ch)
```

**Comment by femtomc** [comment]
I broadly agree with the change in the return value convention. 

I like the calling convention that generative data types come first -- as it reflects your proposed return value convention (and I think, because of that, makes it easier to remember). This is at odds with what Gen.jl does currently.

More information on `generate -> importance` -- I decided this when GenJAX was early after a discussion with Vikash, where he mentioned that `generate` is an overloaded term, and doesn't accurately reflect what actually happens in the semantics of the interface. I agree with him.

I also think we should be careful to solidify the conventions in Gen.jl as "the standard" (although it is the standard implementation) for _all Gen implementations_. **We are not at that stage yet.** There will likely be further changes to the GFI as we progress in research, even if the interfaces we are discussing here are (my opinion) mostly solid.

**Comment by femtomc** [comment]
@mirkoklukas Convention changes like this in the codebase are rather painful -- we should set aside approximately 4-6 hours to do it, and then we need to inform the Google folks (and Nishad, other users, etc).

**Comment by mirkoklukas** [comment]
I agree that gen.jl shouldn't necessarily be the standard. I just think something consistent would be great, across all platforms great, but even within genjax, and something that reflects the use cases.

Also it should be reflect the first class citizens and what the function does. You'd expect `tr.update` to return a trace and some additional relevant information. Same with `importance`.

**Comment by mirkoklukas** [comment]
Re: "generate" vs "importance"
I was wondering why don't we just use `simulate` as well, and have it return the weight as well? Makes the most sense to me actually.

**Comment by femtomc** [comment]
I’m not so sure — what would the weight returned by the simulate “mode” of this new interface be? Always 0?

I think it is important to distinguish interfaces which sample from normalized measures, and only return estimates of their densities (inside the returned trace)  — from the interfaces which utilize internal proposal families and additionally return single sample importance weight estimates of marginals.

The latter is quite different — and I don’t think it behooves the user if we equate them as different modes of a single interface.

**Comment by femtomc** [comment]
@mirkoklukas note there’s also the convention of separating different “modes” of (what could be) a single interface into different interfaces:

e.g. assess is like importance, but you need to provide constraints to every traced choice. Otherwise, it is an error (improper use of the interface)

I think combining existing interfaces must be carefully though out, and we should seek feedback from the wider lab (including e.g. Alex and Xuan — and we should also query the lab about the name change which I performed)

**Comment by mirkoklukas** [comment]
Yes 0. Isn't `simulate` the same as `generate` with an empty choice map?

**Comment by mirkoklukas** [comment]
The different modes make sense. I just havent encountered it too much. Intuitively I just want be able to feed a choicemap to simulate :)

**Comment by sritchie** [comment]
Closing, we can revisit this when we do a pass over Gen.jl and standardize on, e.g., passing PRNGKeys around etc
